// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }


import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Proyecto Luly — Metroidvania",
  description: "Un metroidvania protagonizado por una perrita llamada Luly",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <body style={{ margin: 0, padding: 0, background: "#000", overflow: "hidden" }}>
        {children}
      </body>
    </html>
  )
}